const projectData =[
    {
        id: 1,
        images: "https://i.postimg.cc/xTjt2mnm/finesweet-project.png",
        title: "Finesweet Project",
        cardInfo: "A 10-page Bootstrap-powered multi-page website with responsive design, catering to various devices for optimal user experience" ,
        tagOne: "HTML 5",
        tagTwo: "CSS 3",
        tagThree: "Bootstrap 5",
        tagFour: "Google Fonts",
        tagFive: "FontAwsome",
    },
    {
        id: 2,
        images: "https://i.postimg.cc/cLrhKNK4/Cameron.png",
        title: "Instacam Project",
        cardInfo: "This Cameron project is a one-page Bootstrap-powered website with a responsive design that adapts to various devices for the best user experience.",
        tagSix: "HTML 5",
        tagSeven: "CSS 3",
        tagEight: "Bootstrap 5",
        tagNine: "Google Fonts",
        tagTen: "FontAwsome",
        tagEleven: "jQuery v1.12.4",
    },
    {
        id: 3,
        images: "https://i.postimg.cc/R0xtMrKY/Kotha-Barta.png",
        title: "Kotha Barta",
        cardInfo: "Create account, log in, change profile photo, send friend requests, view, accept, block. Responsive design. Messages, groups, Firebase for data.",
        tagSix: "React JS",
        tagSeven: "Tailwind CSS",
        tagEight: "Node JS",
        tagNine: "Firebase",
        tagTen: "Goole Fonts",
        tagEleven: "React Icons",
    },
    {
        id: 4,
        images: "https://i.postimg.cc/pLVd9884/Summer-Sale.png",
        title: "Summer Sale Project",
        cardInfo: "This Improve extend may be a one-page Bootstrap-powered site with a responsive design that adapts to different gadgets for the most excellent client involvement.",
        tagSix: "HTML 5",
        tagSeven: "Tailwind CSS",
        tagNine: "Google Fonts",
        tagEleven: "JavaScript",
    },
    {
        id: 4,
        images: "https://i.postimg.cc/L8MZXn6Z/Petroil.png",
        title: "Petroil Project",
        cardInfo: "This Improve extend may be a one-page Bootstrap-powered site with a responsive design that adapts to different gadgets for the most excellent client involvement.",
        tagSix: "React JS",
        tagSeven: "Tailwind CSS",
        tagNine: "Google Fonts",
        tagTen: "React Icons",
    },
    {
        id: 4,
        images: "https://i.postimg.cc/x8zdHTzY/E-buy.png",
        title: "E-Buy project",
        cardInfo: "This Improve extend may be a one-page Bootstrap-powered site with a responsive design that adapts to different gadgets for the most excellent client involvement.",
        tagSix: "HTML 5",
        tagSeven: "CSS 3",
        tagEight: "Bootstrap 5",
        tagNine: "Google Fonts",
        tagTen: "FontAwsome",
        tagEleven: "jQuery v1.12.4",
    }
];
export default projectData;